name: Lint
on:
  push:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: cicd-sensor/cicd-sensor-action@6ee257338e68af2b279b321b3346fe5f385aa498 # v0.0.29
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
